language: node_js


node_js:
- '0.12'

# S: Build Lifecycle
install:
- npm install 


before_install:
- npm install hexo-cli
- npm install hexo --save
# - npm install hexo-deployer-git --save 
# - mv _config.yml _config
# - hexo init
# - mv _config _config.yml


# config for `hexo deploy`
- cp .daocloud/id_rsa ~/.ssh/
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .daocloud/ssh_config ~/.ssh/config
- git config --global user.name "zdl411437734"
- git config --global user.email "zdl_411437734@hotmail.com"


script:
- pwd
- ls
- hexo clean
- hexo generate
- hexo deploy


branches:
  only:
  - master